<?php 
date_default_timezone_get('Asia/Shanghai');
session_start();
header('Content-type:text/html;charset=utf-8');
define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASSWORD','');
define('DB_DATABASE','shop');
define('DB_PORT',3306);
 ?>